/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-24 at 01:48:14 UTC 
 * Modify at your own risk.
 */

package com.appspot.passwordgen_msorenson.letmein.model;

/**
 * Model definition for Profile.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the letmein. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Profile extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean digits;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String exclude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer generation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String include;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer length;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean lower;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("modified_at")
  private java.lang.String modifiedAt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean punctuation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String scheme;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean spaces;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean upper;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String url;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String username;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String uuid;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getDigits() {
    return digits;
  }

  /**
   * @param digits digits or {@code null} for none
   */
  public Profile setDigits(java.lang.Boolean digits) {
    this.digits = digits;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getExclude() {
    return exclude;
  }

  /**
   * @param exclude exclude or {@code null} for none
   */
  public Profile setExclude(java.lang.String exclude) {
    this.exclude = exclude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getGeneration() {
    return generation;
  }

  /**
   * @param generation generation or {@code null} for none
   */
  public Profile setGeneration(java.lang.Integer generation) {
    this.generation = generation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInclude() {
    return include;
  }

  /**
   * @param include include or {@code null} for none
   */
  public Profile setInclude(java.lang.String include) {
    this.include = include;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLength() {
    return length;
  }

  /**
   * @param length length or {@code null} for none
   */
  public Profile setLength(java.lang.Integer length) {
    this.length = length;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getLower() {
    return lower;
  }

  /**
   * @param lower lower or {@code null} for none
   */
  public Profile setLower(java.lang.Boolean lower) {
    this.lower = lower;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getModifiedAt() {
    return modifiedAt;
  }

  /**
   * @param modifiedAt modifiedAt or {@code null} for none
   */
  public Profile setModifiedAt(java.lang.String modifiedAt) {
    this.modifiedAt = modifiedAt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Profile setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getPunctuation() {
    return punctuation;
  }

  /**
   * @param punctuation punctuation or {@code null} for none
   */
  public Profile setPunctuation(java.lang.Boolean punctuation) {
    this.punctuation = punctuation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getScheme() {
    return scheme;
  }

  /**
   * @param scheme scheme or {@code null} for none
   */
  public Profile setScheme(java.lang.String scheme) {
    this.scheme = scheme;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getSpaces() {
    return spaces;
  }

  /**
   * @param spaces spaces or {@code null} for none
   */
  public Profile setSpaces(java.lang.Boolean spaces) {
    this.spaces = spaces;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getUpper() {
    return upper;
  }

  /**
   * @param upper upper or {@code null} for none
   */
  public Profile setUpper(java.lang.Boolean upper) {
    this.upper = upper;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUrl() {
    return url;
  }

  /**
   * @param url url or {@code null} for none
   */
  public Profile setUrl(java.lang.String url) {
    this.url = url;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUsername() {
    return username;
  }

  /**
   * @param username username or {@code null} for none
   */
  public Profile setUsername(java.lang.String username) {
    this.username = username;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUuid() {
    return uuid;
  }

  /**
   * @param uuid uuid or {@code null} for none
   */
  public Profile setUuid(java.lang.String uuid) {
    this.uuid = uuid;
    return this;
  }

  @Override
  public Profile set(String fieldName, Object value) {
    return (Profile) super.set(fieldName, value);
  }

  @Override
  public Profile clone() {
    return (Profile) super.clone();
  }

}
