/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-24 at 01:48:14 UTC 
 * Modify at your own risk.
 */

package com.appspot.passwordgen_msorenson.letmein.model;

/**
 * Model definition for SyncRequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the letmein. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SyncRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("previous_sync_at")
  private java.lang.String previousSyncAt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Profile> profiles;

  static {
    // hack to force ProGuard to consider Profile used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Profile.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("synced_at")
  private java.lang.String syncedAt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String verify;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public SyncRequest setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPreviousSyncAt() {
    return previousSyncAt;
  }

  /**
   * @param previousSyncAt previousSyncAt or {@code null} for none
   */
  public SyncRequest setPreviousSyncAt(java.lang.String previousSyncAt) {
    this.previousSyncAt = previousSyncAt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Profile> getProfiles() {
    return profiles;
  }

  /**
   * @param profiles profiles or {@code null} for none
   */
  public SyncRequest setProfiles(java.util.List<Profile> profiles) {
    this.profiles = profiles;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSyncedAt() {
    return syncedAt;
  }

  /**
   * @param syncedAt syncedAt or {@code null} for none
   */
  public SyncRequest setSyncedAt(java.lang.String syncedAt) {
    this.syncedAt = syncedAt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getVerify() {
    return verify;
  }

  /**
   * @param verify verify or {@code null} for none
   */
  public SyncRequest setVerify(java.lang.String verify) {
    this.verify = verify;
    return this;
  }

  @Override
  public SyncRequest set(String fieldName, Object value) {
    return (SyncRequest) super.set(fieldName, value);
  }

  @Override
  public SyncRequest clone() {
    return (SyncRequest) super.clone();
  }

}
